version: '3'

services:
  publish-subscribe:
    build: 
      dockerfile: Dockerfile
    command: ["tail -f /dev/null"]
    volumes:
      - ..:/publish-subscribe

  rabbitmq:
    image: rabbitmq:3-management-alpine