version: '3'

services:
  workqueues:
    build: 
      dockerfile: Dockerfile
    command: ["tail -f /dev/null"]
    volumes:
      - ..:/workqueues

  rabbitmq:
    image: rabbitmq:3-management-alpine