version: '3'

services:
  topics:
    build: 
      dockerfile: Dockerfile
    command: ["tail -f /dev/null"]
    volumes:
      - ..:/topics

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"