version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  helloworld:
    build:
      dockerfile: Dockerfile
    command: ["tail -f /dev/null"]
    volumes:
      - ..:/my-folder-for-work

networks:
  default:
    driver: bridge

